# Generated by Django 5.2.5 on 2025-08-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wasteentry',
            options={'verbose_name_plural': 'Waste Entries'},
        ),
    ]
